#Common
common_params:
  verbosity: 2                         # Debug Output, 0: only important events, 1: optimization duration, 2: added factors
  reLocalizeWorldToMapAtStart: true    # Whether the World->Map transform should be updated in the beginning (odom start at identity)
